# Generated by Django 5.2.16 on 2026-07-11 09:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0004_role_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_user_avatar',
            },
        ),
        migrations.CreateModel(
            name='PresenceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField(default=0.5)),
                ('y', models.FloatField(default=0.5)),
                ('facing', models.CharField(choices=[('down', 'down'), ('up', 'up'), ('left', 'left'), ('right', 'right')], default='down', max_length=8)),
                ('manual_status', models.CharField(blank=True, max_length=16, null=True)),
                ('manual_status_at', models.DateTimeField(blank=True, null=True)),
                ('busy_until', models.DateTimeField(blank=True, null=True)),
                ('meeting_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_moved', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='identity.workspacemodel')),
            ],
            options={
                'db_table': 'presence_presence',
                'indexes': [models.Index(fields=['workspace', 'last_seen'], name='presence_pr_workspa_369840_idx')],
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
