# Generated by Django 5.2.16 on 2026-07-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencemodel',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
