# Generated by Django 5.2.16 on 2026-07-29 00:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('presence', '0002_presence_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskAssignmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.PositiveSmallIntegerField()),
                ('seat_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_assignments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_assignments', to='identity.workspacemodel')),
            ],
            options={
                'db_table': 'presence_desk_assignment',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'floor', 'seat_id'), name='uniq_desk_per_seat'), models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_desk_per_user')],
            },
        ),
    ]
