# Generated by Django 5.2.8 on 2026-06-27 05:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_password_reset'),
        ('projects', '0004_cardmodel_due_date_cardmodel_reporter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando'), ('voting', 'Votando'), ('revealed', 'Revelado'), ('done', 'Concluído')], default='waiting', max_length=20)),
                ('current_card_id', models.UUIDField(blank=True, null=True)),
                ('card_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_poker_sessions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_sessions', to='projects.projectmodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_sessions', to='identity.workspacemodel')),
            ],
            options={
                'db_table': 'estimation_poker_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PokerParticipantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_host', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='estimation.pokersessionmodel')),
            ],
            options={
                'db_table': 'estimation_poker_participant',
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PokerVoteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_id', models.UUIDField()),
                ('value', models.CharField(blank=True, max_length=10, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='estimation.pokerparticipantmodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='estimation.pokersessionmodel')),
            ],
            options={
                'db_table': 'estimation_poker_vote',
                'unique_together': {('session', 'card_id', 'participant')},
            },
        ),
    ]
