# Generated by Django 5.2.15 on 2026-07-05 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerRoundModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_id', models.UUIDField()),
                ('card_ref', models.CharField(blank=True, default='', max_length=20)),
                ('card_title', models.CharField(blank=True, default='', max_length=200)),
                ('final_points', models.PositiveSmallIntegerField()),
                ('votes', models.JSONField(default=list)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_poker_rounds', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='estimation.pokersessionmodel')),
            ],
            options={
                'db_table': 'estimation_poker_round',
                'ordering': ['decided_at'],
            },
        ),
    ]
