# Generated by Django 5.2.15 on 2026-07-29 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_pokerroundmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerReactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_reactions_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='estimation.pokersessionmodel')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_reactions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estimation_poker_reaction',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='estimation__session_42c810_idx')],
            },
        ),
    ]
