# Generated by Django 5.2.16 on 2026-08-12 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_pokerreactionmodel_emote_and_more'),
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('projects', '0028_mark_doing_as_working'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokersessionmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poker_sessions', to='projects.projectmodel'),
        ),
        migrations.CreateModel(
            name='SquadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='identity.workspacemodel')),
            ],
            options={
                'db_table': 'estimation_squad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SquadMemberModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_memberships', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='estimation.squadmodel')),
            ],
            options={
                'db_table': 'estimation_squad_member',
            },
        ),
        migrations.AddField(
            model_name='pokersessionmodel',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poker_sessions', to='estimation.squadmodel'),
        ),
        migrations.AddConstraint(
            model_name='squadmodel',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_squad_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='squadmembermodel',
            constraint=models.UniqueConstraint(fields=('squad', 'user'), name='uniq_member_per_squad'),
        ),
    ]
