# Generated by Django 5.2.16 on 2026-08-26
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("estimation", "0005_squads")]

    operations = [
        migrations.AddField(
            model_name="pokersessionmodel",
            name="presented_card_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
