# Generated by Django 5.2.15 on 2026-07-05 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDevLinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('repo_full_name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('branch', 'Branch'), ('commit', 'Commit'), ('pull_request', 'Pull Request')], max_length=15)),
                ('external_id', models.CharField(max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('author_login', models.CharField(blank=True, max_length=100)),
                ('author_avatar', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'github_card_dev_link',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('card_id', 'kind', 'external_id'), name='uniq_card_dev_link')],
            },
        ),
        migrations.CreateModel(
            name='GithubConnectionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_login', models.CharField(blank=True, max_length=100)),
                ('github_avatar', models.URLField(blank=True)),
                ('access_token', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('revoked', 'Revogada')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão GitHub',
                'verbose_name_plural': 'Conexões GitHub',
                'db_table': 'github_connection',
            },
        ),
        migrations.CreateModel(
            name='GithubOAuthStateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('return_to', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'github_oauth_state',
            },
        ),
        migrations.CreateModel(
            name='GithubRepoLinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('full_name', models.CharField(max_length=200)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('webhook_id', models.BigIntegerField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'github_repo_link',
                'constraints': [models.UniqueConstraint(fields=('project_id', 'full_name'), name='uniq_project_repo')],
            },
        ),
    ]
