# Generated by Django 5.2.8 on 2026-06-27 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_password_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('audio', 'Áudio')], default='text', max_length=10)),
                ('text', models.TextField(help_text='Texto extraído do documento')),
                ('status', models.CharField(choices=[('uploaded', 'Importado'), ('analyzed', 'Analisado'), ('failed', 'Falhou')], default='uploaded', max_length=10)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'copilot_document',
                'ordering': ['-created_at'],
            },
        ),
    ]
