# Generated by Django 5.2.15 on 2026-07-05 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_workspaceaiconfigmodel'),
        ('identity', '0003_password_reset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Mensagem no chat'), ('analyze', 'Documento analisado'), ('cards', 'Cards criados pela IA'), ('agent_execute', 'Ações do agente executadas'), ('rating', 'Avaliação da resposta')], max_length=20)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_events', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Evento do Copiloto',
                'verbose_name_plural': 'Eventos do Copiloto',
                'db_table': 'copilot_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'kind', 'created_at'], name='copilot_eve_workspa_0dd501_idx')],
            },
        ),
    ]
