# Generated by Django 5.2.15 on 2026-07-17 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0003_copiloteventmodel'),
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceBrandKitModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tone_of_voice', models.TextField(blank=True, default='', help_text='Como a marca fala (ex.: próxima, jovem, sem jargão)')),
                ('colors', models.JSONField(blank=True, default=list)),
                ('fonts', models.CharField(blank=True, default='', max_length=200)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('guidelines', models.TextField(blank=True, default='', help_text='Diretrizes livres (o que evitar, termos etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Kit de marca',
                'verbose_name_plural': 'Kits de marca',
                'db_table': 'copilot_brand_kit',
            },
        ),
    ]
