# Generated by Django 5.2.15 on 2026-07-17 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0004_workspacebrandkitmodel'),
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(help_text='instagram, linkedin, facebook…', max_length=30)),
                ('account_name', models.CharField(help_text='@handle ou nome da página', max_length=120)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Conta social',
                'verbose_name_plural': 'Contas sociais',
                'db_table': 'copilot_social_account',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'channel'), name='unique_workspace_social_channel')],
            },
        ),
    ]
