# Generated by Django 5.2.15 on 2026-07-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0005_socialaccountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccountmodel',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='socialaccountmodel',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialaccountmodel',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
