# Generated by Django 5.2.16 on 2026-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0006_socialaccountmodel_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceaiconfigmodel',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI'), ('google', 'Google (Gemini)')], default='anthropic', max_length=20),
        ),
    ]
