# Generated by Django 5.2.16 on 2026-08-31 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0007_alter_workspaceaiconfigmodel_provider'),
        ('projects', '0047_fix_orphan_subtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copilot_documents', to='projects.projectmodel'),
        ),
    ]
