# Generated by Django 5.2.16 on 2026-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0008_documentmodel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='copilot_documents/'),
        ),
    ]
