# Generated by Django 5.2.15 on 2026-07-27 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatwootConnectionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.CharField(help_text='URL da instância, ex.: https://app.chatwoot.com ou https://chat.t4e.com.br', max_length=300)),
                ('account_id', models.PositiveIntegerField(help_text='ID da conta no Chatwoot')),
                ('access_token_encrypted', models.TextField(blank=True, default='', help_text='api_access_token do agente/bot (cifrado)')),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('connected', 'Conectada'), ('error', 'Com erro'), ('disconnected', 'Desconectada')], default='disconnected', max_length=14)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=160)),
                ('agent_email', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_connection', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Conexão Chatwoot',
                'verbose_name_plural': 'Conexões Chatwoot',
                'db_table': 'chatwoot_connection',
            },
        ),
        migrations.CreateModel(
            name='ConversationLinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.PositiveIntegerField(help_text='ID da conversa no Chatwoot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatwoot_conversations', to='sales.customermodel')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatwoot_conversations', to='sales.dealmodel')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_links', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Vínculo de conversa',
                'verbose_name_plural': 'Vínculos de conversa',
                'db_table': 'chatwoot_conversation_link',
                'indexes': [models.Index(fields=['deal'], name='chatwoot_co_deal_id_fa6f0c_idx'), models.Index(fields=['customer'], name='chatwoot_co_custome_8bf36a_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'conversation_id'), name='uniq_chatwoot_link_ws_conv')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='message_created, conversation_updated…', max_length=60)),
                ('conversation_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_events', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Evento de webhook',
                'verbose_name_plural': 'Eventos de webhook',
                'db_table': 'chatwoot_webhook_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='idx_cw_event_ws_at'), models.Index(fields=['conversation_id'], name='idx_cw_event_conv')],
            },
        ),
    ]
