# Generated by Django 5.2.8 on 2026-06-25 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do projeto', max_length=120)),
                ('key', models.CharField(help_text='Prefixo curto do ID dos cards (ex: MIA)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projects_project',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'key'), name='unique_workspace_project_key')],
            },
        ),
    ]
