# Generated by Django 5.2.8 on 2026-06-27 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(help_text='Número sequencial no projeto (ex.: 142)')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'A fazer'), ('doing', 'Em andamento'), ('review', 'Em revisão'), ('done', 'Concluído')], default='todo', max_length=10)),
                ('type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('debt', 'Débito técnico'), ('spike', 'Spike'), ('chore', 'Tarefa')], default='feature', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10)),
                ('points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Ordem dentro da coluna')),
                ('source', models.CharField(default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.projectmodel')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'projects_card',
                'ordering': ['status', 'order', 'number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'number'), name='unique_project_card_number')],
            },
        ),
    ]
