# Generated by Django 5.2.8 on 2026-06-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_cardmodel_due_date_cardmodel_reporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='projects.cardmodel'),
        ),
    ]
