# Generated by Django 5.2.8 on 2026-06-27 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_cardmodel_labels_cardmodel_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('relates', 'Relacionado a'), ('blocks', 'Bloqueia'), ('duplicates', 'Duplica')], default='relates', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='projects.cardmodel')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='projects.cardmodel')),
            ],
            options={
                'verbose_name': 'Vínculo de card',
                'verbose_name_plural': 'Vínculos de card',
                'db_table': 'projects_issue_link',
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'link_type'), name='unique_issue_link')],
            },
        ),
    ]
