# Generated by Django 5.2.15 on 2026-06-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_cardhistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('debt', 'Débito técnico'), ('spike', 'Spike'), ('chore', 'Tarefa'), ('epic', 'Épico')], default='feature', max_length=10),
        ),
    ]
