# Generated by Django 5.2.15 on 2026-06-27 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_epic_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveIntegerField(default=0, help_text='Tamanho em bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.cardmodel')),
            ],
            options={
                'db_table': 'projects_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_components', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_component',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção única'), ('multiselect', 'Seleção múltipla'), ('checkbox', 'Checkbox'), ('user', 'Usuário')], default='text', max_length=15)),
                ('options', models.JSONField(blank=True, default=list, help_text='Opções para select/multiselect')),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_custom_field',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VersionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('released', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorklogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_seconds', models.PositiveIntegerField(help_text='Segundos trabalhados')),
                ('started_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='projects.cardmodel')),
            ],
            options={
                'db_table': 'projects_worklog',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CardComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_components', to='projects.cardmodel')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.componentmodel')),
            ],
            options={
                'db_table': 'projects_card_component',
                'unique_together': {('card', 'component')},
            },
        ),
        migrations.CreateModel(
            name='IssueFieldValueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='projects.cardmodel')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='projects.customfieldmodel')),
            ],
            options={
                'db_table': 'projects_issue_field_value',
                'unique_together': {('card', 'field')},
            },
        ),
        migrations.CreateModel(
            name='CardVersionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_versions', to='projects.cardmodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.versionmodel')),
            ],
            options={
                'db_table': 'projects_card_version',
                'unique_together': {('card', 'version')},
            },
        ),
    ]
