# Generated by Django 5.2.8 on 2026-06-27 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_versions_components_worklogs_attachments_customfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='status',
            field=models.CharField(default='todo', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkflowStatusModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('todo', 'A fazer'), ('in_progress', 'Em andamento'), ('done', 'Concluído')], default='todo', max_length=20)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_statuses', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_workflow_status',
                'ordering': ['order'],
                'unique_together': {('project', 'slug')},
            },
        ),
    ]
