# Generated by Django 5.2.8 on 2026-06-27 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_workflow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRuleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('cron', 'Agendado (cron)'), ('status_changed', 'Status alterado'), ('card_created', 'Card criado')], max_length=30)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('action_type', models.CharField(choices=[('change_status', 'Alterar status'), ('assign_user', 'Atribuir usuário'), ('add_label', 'Adicionar label'), ('remove_label', 'Remover label'), ('set_priority', 'Alterar prioridade')], max_length=30)),
                ('action_config', models.JSONField(default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_automation_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRunLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_by', models.CharField(default='cron', max_length=20)),
                ('cards_affected', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='projects.automationrulemodel')),
            ],
            options={
                'db_table': 'projects_automation_run_log',
                'ordering': ['-ran_at'],
            },
        ),
    ]
