# Generated by Django 5.2.8 on 2026-06-27 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_automation_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('type', models.CharField(choices=[('card_assigned', 'Card atribuído'), ('card_commented', 'Comentário adicionado'), ('card_status_changed', 'Status alterado'), ('automation_ran', 'Automação executada'), ('sprint_started', 'Sprint iniciada')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=300)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
