# Generated by Django 5.2.15 on 2026-07-15 22:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmodel',
            options={'ordering': ['status', 'rank', 'order', 'number'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='approval_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='attachmentmodel',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='publish_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='template',
            field=models.CharField(default='software', max_length=20),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug'), ('debt', 'Débito técnico'), ('spike', 'Spike'), ('chore', 'Tarefa'), ('epic', 'Épico'), ('post', 'Post'), ('peca', 'Peça'), ('campanha', 'Campanha'), ('artigo', 'Artigo'), ('email', 'E-mail')], default='feature', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('card_assigned', 'Card atribuído'), ('card_commented', 'Comentário adicionado'), ('card_status_changed', 'Status alterado'), ('card_approval', 'Peça aprovada/reprovada'), ('automation_ran', 'Automação executada'), ('sprint_started', 'Sprint iniciada')], max_length=40),
        ),
    ]
