# Generated by Django 5.2.15 on 2026-07-28 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_cardmetricmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='avatar_color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='avatar_emoji',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='avatar_image',
            field=models.FileField(blank=True, null=True, upload_to='project-avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='category',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='default_assignee_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='lead_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstatusmodel',
            name='wip_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BoardConfigModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('swimlane_mode', models.CharField(choices=[('none', 'Sem agrupamento'), ('epic', 'Epic'), ('assignee', 'Responsável'), ('priority', 'Prioridade'), ('subtask', 'Subtarefa')], default='none', max_length=12)),
                ('card_fields', models.JSONField(blank=True, default=list)),
                ('card_color_rule', models.CharField(choices=[('none', 'Sem cor'), ('priority', 'Prioridade'), ('issue_type', 'Tipo do ticket'), ('assignee', 'Responsável'), ('epic', 'Epic')], default='none', max_length=12)),
                ('card_color_map', models.JSONField(blank=True, default=dict)),
                ('hide_done_after_days', models.PositiveSmallIntegerField(default=0)),
                ('sprints_enabled', models.BooleanField(default=True)),
                ('estimation_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_config', to='projects.projectmodel')),
            ],
            options={
                'verbose_name': 'Configuração de quadro',
                'verbose_name_plural': 'Configurações de quadro',
                'db_table': 'projects_board_config',
            },
        ),
    ]
