# Generated by Django 5.2.16 on 2026-07-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_cardmetricmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='working_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
