# Generated by Django 5.2.15 on 2026-07-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_board_config'),
        ('projects', '0019_cardmodel_working_note'),
    ]

    operations = [
    ]
