# Generated by Django 5.2.15 on 2026-07-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_board_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='avatar_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
