# Generated by Django 5.2.15 on 2026-07-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_avatar_data_uri'),
        ('projects', '0020_merge_0019_board_config_0019_cardmodel_working_note'),
    ]

    operations = [
    ]
