# Generated by Django 5.2.16 on 2026-07-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_merge_20260729_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='original_estimate_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='remaining_estimate_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='resolution',
            field=models.CharField(blank=True, choices=[('done', 'Entregue'), ('wont_do', 'Não será feito'), ('duplicate', 'Duplicado'), ('cannot_reproduce', 'Não reproduzido'), ('incomplete', 'Incompleto')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
