# Generated by Django 5.2.15 on 2026-07-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_backfill_card_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('card_assigned', 'Card atribuído'), ('card_commented', 'Comentário adicionado'), ('card_status_changed', 'Status alterado'), ('card_approval', 'Peça aprovada/reprovada'), ('automation_ran', 'Automação executada'), ('sprint_started', 'Sprint iniciada'), ('meeting_reminder', 'Lembrete de reunião')], max_length=40),
        ),
    ]
