# Generated by Django 5.2.16 on 2026-08-10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0023_backfill_card_resolution"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousReportModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conduct", "Conduta inadequada"),
                            ("harassment", "Assédio ou discriminação"),
                            ("security", "Segurança ou saúde"),
                            ("fraud", "Fraude ou irregularidade"),
                            ("other", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Denúncia anônima",
                "verbose_name_plural": "Denúncias anônimas",
                "db_table": "projects_anonymous_report",
            },
        ),
    ]
