# Generated by Django 5.2.16 on 2026-08-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_notificationmodel_type'),
        ('projects', '0024_anonymous_report'),
    ]

    operations = [
    ]
