# Generated by Django 5.2.16 on 2026-08-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_merge_20260810_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcommentmodel',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='external_assignee',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='sprintmodel',
            name='external_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
    ]
