# Generated by Django 5.2.16 on 2026-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_jira_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstatusmodel',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
