# Generated by Django 5.2.16 on 2026-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_mark_doing_as_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='visibility',
            field=models.CharField(choices=[('restricted', 'Restrito a quem tem acesso'), ('workspace', 'Todo o workspace')], db_index=True, default='restricted', max_length=12),
        ),
    ]
