# Generated by Django 5.2.16 on 2026-08-12 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_squads'),
        ('projects', '0029_project_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='estimation.squadmodel'),
        ),
    ]
