# Generated by Django 5.2.16 on 2026-08-17 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDeleteGrantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_grants', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_project_delete_grant',
                'unique_together': {('project', 'user_id')},
            },
        ),
    ]
