# Generated by Django 5.2.16 on 2026-08-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_projectdeletegrantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstatusmodel',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
