# Generated by Django 5.2.16 on 2026-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_workflowstatusmodel_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='public_allow_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='public_token',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, unique=True),
        ),
    ]
