# Generated by Django 5.2.16 on 2026-08-17 21:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projectmodel_public_allow_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='public_message_code',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='BoardMessageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, default='', max_length=80)),
                ('body', models.TextField()),
                ('from_team', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_messages', to='projects.projectmodel')),
            ],
            options={
                'db_table': 'projects_board_message',
                'ordering': ['created_at'],
            },
        ),
    ]
