# Generated by Django 5.2.16 on 2026-08-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectmodel_public_message_code_boardmessagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='type',
            field=models.CharField(choices=[('card_assigned', 'Card atribuído'), ('card_commented', 'Comentário adicionado'), ('card_status_changed', 'Status alterado'), ('card_approval', 'Peça aprovada/reprovada'), ('automation_ran', 'Automação executada'), ('sprint_started', 'Sprint iniciada'), ('meeting_reminder', 'Lembrete de reunião'), ('board_message', 'Mensagem no mural')], max_length=40),
        ),
    ]
