# Generated by Django 5.2.16 on 2026-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_rename_public_message_code_to_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='type',
            field=models.CharField(choices=[('feature', 'História'), ('bug', 'Bug'), ('debt', 'Débito técnico'), ('spike', 'Spike'), ('chore', 'Tarefa'), ('epic', 'Épico'), ('post', 'Post'), ('peca', 'Peça'), ('campanha', 'Campanha'), ('artigo', 'Artigo'), ('email', 'E-mail')], default='feature', max_length=10),
        ),
    ]
