# Generated by Django 5.2.16 on 2026-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_backfill_card_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
