# Generated by Django 5.2.16 on 2026-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_alter_attachmentmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
