# Generated by Django 5.2.16 on 2026-08-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_cardmodel_flagged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmodel',
            options={'ordering': ['status', '-flagged', 'rank', 'order', 'number'], 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
    ]
