# Generated by Django 5.2.16 on 2026-08-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_cardmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmessagemodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='projects.boardmessagemodel'),
        ),
    ]
