# Generated by Django 5.2.16 on 2026-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_boardmessagemodel_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='mural_notification_excluded_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
