# Generated by Django 5.2.17 on 2026-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_projectmodel_mural_notification_excluded_user_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardconfigmodel',
            name='hide_done_after_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
