# Generated by Django 5.2.17 on 2026-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_cardcommentmodel_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='reporter_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
