# Generated by Django 5.2.16 on 2026-09-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_cardmodel_reporter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstatusmodel',
            name='is_sprint_entry',
            field=models.BooleanField(default=False),
        ),
    ]
