# Generated by Django 5.2.15 on 2026-06-26 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skin', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
                ('cloth', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('hair', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('accessory', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0)),
                ('configured', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Avatar',
                'db_table': 'office_avatar_profile',
            },
        ),
        migrations.CreateModel(
            name='DeskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=40)),
                ('group_number', models.SmallIntegerField()),
                ('position_in_group', models.SmallIntegerField()),
                ('tile_x', models.SmallIntegerField()),
                ('tile_y', models.SmallIntegerField()),
                ('is_fixed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_desk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesa',
                'db_table': 'office_desk',
                'ordering': ['group_number', 'position_in_group'],
            },
        ),
        migrations.CreateModel(
            name='DeskSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='office.deskmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Mesa',
                'db_table': 'office_desk_session',
            },
        ),
        migrations.CreateModel(
            name='DeskCardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'Em progresso'), ('reviewing', 'Em revisão'), ('blocked', 'Bloqueado'), ('meeting', 'Reunião'), ('afk', 'Ausente')], default='in_progress', max_length=20)),
                ('eta', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desk_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='office.desksessionmodel')),
            ],
            options={
                'verbose_name': 'Card de Desk',
                'db_table': 'office_desk_card',
            },
        ),
    ]
