# Generated by Django 5.2.15 on 2026-07-22 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('projects', '0018_cardmetricmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('company', 'Empresa'), ('person', 'Pessoa física')], default='company', max_length=10)),
                ('name', models.CharField(help_text='Nome fantasia ou nome da pessoa', max_length=160)),
                ('legal_name', models.CharField(blank=True, default='', help_text='Razão social', max_length=160)),
                ('document', models.CharField(blank=True, default='', help_text='CNPJ ou CPF', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'sales_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, default='', help_text='Cargo/função', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_primary', models.BooleanField(default=False, help_text='Contato principal do cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sales.customermodel')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'db_table': 'sales_contact',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DealModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', help_text='Origem do lead', max_length=60)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=120)),
                ('lost_notes', models.TextField(blank=True, default='')),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('rank', models.CharField(blank=True, default='', help_text='Lexorank na coluna', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='sales.contactmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='sales.customermodel')),
                ('delivery_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_deals', to='projects.projectmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
                'db_table': 'sales_deal',
                'ordering': ['rank', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=40)),
                ('from_value', models.TextField(blank=True, default='')),
                ('to_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_changes', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales.dealmodel')),
            ],
            options={
                'verbose_name': 'Histórico do negócio',
                'verbose_name_plural': 'Históricos do negócio',
                'db_table': 'sales_deal_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivityModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('task', 'Tarefa'), ('meeting', 'Reunião')], default='note', max_length=10)),
                ('content', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Fim da reunião', null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('meet_url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deal_activities', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_deal_activities', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.dealmodel')),
            ],
            options={
                'verbose_name': 'Atividade do negócio',
                'verbose_name_plural': 'Atividades do negócio',
                'db_table': 'sales_deal_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('probability_default', models.PositiveSmallIntegerField(default=0, help_text='Probabilidade padrão (0–100) aplicada ao entrar no estágio')),
                ('kind', models.CharField(choices=[('open', 'Aberto'), ('won', 'Ganho'), ('lost', 'Perdido')], default='open', max_length=10)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Estágio do funil',
                'verbose_name_plural': 'Estágios do funil',
                'db_table': 'sales_pipeline_stage',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dealmodel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='sales.pipelinestagemodel'),
        ),
        migrations.AddIndex(
            model_name='customermodel',
            index=models.Index(fields=['workspace', 'name'], name='sales_custo_workspa_b16e04_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivitymodel',
            index=models.Index(fields=['assignee', 'due_date'], name='sales_deal__assigne_e2fc8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestagemodel',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_workspace_stage_slug'),
        ),
        migrations.AddIndex(
            model_name='dealmodel',
            index=models.Index(fields=['workspace', 'stage'], name='sales_deal_workspa_f1fa25_idx'),
        ),
        migrations.AddIndex(
            model_name='dealmodel',
            index=models.Index(fields=['workspace', 'expected_close_date'], name='sales_deal_workspa_1ae329_idx'),
        ),
    ]
