# Generated by Django 5.2.15 on 2026-07-28 00:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('accepted', 'Aceita'), ('rejected', 'Recusada')], default='draft', max_length=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('intro', models.TextField(blank=True, default='', help_text='Texto de abertura')),
                ('terms', models.TextField(blank=True, default='', help_text='Condições comerciais')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(blank=True, default='', max_length=254)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_proposals', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='sales.dealmodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'sales_proposal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLineItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.proposalmodel')),
            ],
            options={
                'verbose_name': 'Item da proposta',
                'verbose_name_plural': 'Itens da proposta',
                'db_table': 'sales_proposal_line_item',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='proposalmodel',
            index=models.Index(fields=['workspace', 'status'], name='sales_propo_workspa_52c922_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalmodel',
            index=models.Index(fields=['deal'], name='sales_propo_deal_id_10f27f_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposalmodel',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='uniq_proposal_number_per_workspace'),
        ),
    ]
