# Generated by Django 5.2.16 on 2026-07-28 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('sales', '0002_proposalmodel_proposallineitemmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('company', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('source', models.CharField(blank=True, default='', help_text='site, indicação, evento, csv_import…', max_length=60)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualifying', 'Qualificando'), ('qualified', 'Qualificado'), ('disqualified', 'Desqualificado'), ('converted', 'Convertido')], default='new', max_length=15)),
                ('disqualify_reason', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('first_contact_due_at', models.DateTimeField(help_text='Prazo do SLA de primeiro contato')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='sales.customermodel')),
                ('converted_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='sales.dealmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'sales_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='sales_lead_workspa_0a0343_idx'), models.Index(fields=['workspace', 'owner'], name='sales_lead_workspa_9cd748_idx')],
            },
        ),
    ]
