# Generated by Django 5.2.15 on 2026-07-28 01:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('sales', '0003_leadmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGoalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='Mês da meta no formato AAAA-MM', max_length=7)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Meta comercial',
                'verbose_name_plural': 'Metas comerciais',
                'db_table': 'sales_goal',
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['workspace', 'period'], name='sales_goal_workspa_1472f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'period', 'owner'), name='unique_sales_goal_per_scope')],
            },
        ),
    ]
