from django.urls import path

from contexts.estimation.interface.api.views import (
    PokerApplyPointsView,
    PokerCardsView,
    PokerHeartbeatView,
    PokerJoinView,
    PokerLeaveView,
    PokerReactionView,
    PokerRoundListView,
    PokerSessionDetailView,
    PokerSessionListCreateView,
    PokerVoteView,
    PokerWorkspaceSummaryView,
    ProjectPokerListCreateView,
    SquadDetailView,
    SquadListCreateView,
)

urlpatterns = [
    path(
        "workspaces/<str:workspace_id>/squads/",
        SquadListCreateView.as_view(),
        name="squad-list-create",
    ),
    path("squads/<str:squad_id>/", SquadDetailView.as_view(), name="squad-detail"),
    path(
        "workspaces/<str:workspace_id>/poker/",
        PokerSessionListCreateView.as_view(),
        name="poker-list-create",
    ),
    path(
        "workspaces/<str:workspace_id>/poker/summary/",
        PokerWorkspaceSummaryView.as_view(),
        name="poker-summary",
    ),
    path(
        "projects/<str:project_id>/poker/",
        ProjectPokerListCreateView.as_view(),
        name="project-poker-list-create",
    ),
    path(
        "poker/<str:session_id>/apply/",
        PokerApplyPointsView.as_view(),
        name="poker-apply",
    ),
    path(
        "poker/<str:session_id>/",
        PokerSessionDetailView.as_view(),
        name="poker-detail",
    ),
    path(
        "poker/<str:session_id>/join/",
        PokerJoinView.as_view(),
        name="poker-join",
    ),
    path(
        "poker/<str:session_id>/leave/",
        PokerLeaveView.as_view(),
        name="poker-leave",
    ),
    path(
        "poker/<str:session_id>/reactions/",
        PokerReactionView.as_view(),
        name="poker-reactions",
    ),
    path(
        "poker/<str:session_id>/heartbeat/",
        PokerHeartbeatView.as_view(),
        name="poker-heartbeat",
    ),
    path(
        "poker/<str:session_id>/vote/",
        PokerVoteView.as_view(),
        name="poker-vote",
    ),
    path(
        "poker/<str:session_id>/cards/",
        PokerCardsView.as_view(),
        name="poker-cards",
    ),
    path(
        "poker/<str:session_id>/rounds/",
        PokerRoundListView.as_view(),
        name="poker-rounds",
    ),
]
