# Generated by Django 5.2.15 on 2026-07-17 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copilot', '0005_socialaccountmodel'),
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('projects', '0018_cardmetricmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJobModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('jira', 'Jira'), ('trello', 'Trello')], max_length=10)),
                ('preview', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('done', 'Concluída'), ('failed', 'Falhou')], default='preview', max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='projects.projectmodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Importação externa',
                'verbose_name_plural': 'Importações externas',
                'db_table': 'integrations_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPostModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_id', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField()),
                ('media_url', models.CharField(blank=True, default='', max_length=500)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('published', 'Publicado'), ('failed', 'Falhou')], default='scheduled', max_length=12)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('error', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='copilot.socialaccountmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='projects.projectmodel')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Post agendado',
                'verbose_name_plural': 'Posts agendados',
                'db_table': 'integrations_scheduled_post',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMetricModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='integrations.scheduledpostmodel')),
            ],
            options={
                'verbose_name': 'Métrica de post',
                'verbose_name_plural': 'Métricas de posts',
                'db_table': 'integrations_post_metric',
            },
        ),
    ]
