# Generated by Django 5.2.15 on 2026-07-18 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialOAuthStateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('workspace_id', models.UUIDField()),
                ('code_verifier', models.CharField(blank=True, default='', max_length=200)),
                ('return_to', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'State OAuth social',
                'verbose_name_plural': 'States OAuth sociais',
                'db_table': 'integrations_social_oauth_state',
            },
        ),
    ]
