# Generated by Django 5.2.15 on 2026-07-20 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('integrations', '0002_socialoauthstatemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAppCredentialModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_app_credentials', to='identity.workspacemodel')),
            ],
            options={
                'verbose_name': 'Credencial de app social',
                'verbose_name_plural': 'Credenciais de apps sociais',
                'db_table': 'integrations_social_app_credential',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider'), name='uniq_social_app_cred_ws_provider')],
            },
        ),
    ]
