# Generated by Django 5.2.15 on 2026-07-20 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0006_socialaccountmodel_external_id_and_more'),
        ('identity', '0005_alter_roleauditlog_actor_id_and_more'),
        ('integrations', '0003_socialappcredentialmodel'),
        ('projects', '0018_cardmetricmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpostmodel',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledpostmodel',
            name='media_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduledpostmodel',
            name='mentions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduledpostmodel',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scheduledpostmodel',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_post_status_sched'),
        ),
    ]
