# Generated by Django 5.2.16 on 2026-08-25
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0011_membershipmodel_allowed_spaces"),
        ("integrations", "0004_scheduledpostmodel_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDriveConfigModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_id_encrypted", models.TextField(blank=True, default="")),
                ("client_secret_encrypted", models.TextField(blank=True, default="")),
                ("refresh_token_encrypted", models.TextField(blank=True, default="")),
                ("takes_folder_id_encrypted", models.TextField(blank=True, default="")),
                ("projects_folder_id_encrypted", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="drive_config", to="identity.workspacemodel")),
            ],
            options={
                "db_table": "integrations_workspace_drive_config",
                "verbose_name": "Configuração Google Drive",
                "verbose_name_plural": "Configurações Google Drive",
            },
        ),
    ]
