# Generated by Django 5.2.16 on 2026-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroommodel',
            name='kind',
            field=models.CharField(choices=[('meeting', 'Reunião'), ('office', 'Andar do Escritório'), ('poker', 'Planning Poker')], db_index=True, default='meeting', max_length=10),
        ),
    ]
