# Generated by Django 5.2.16 on 2026-08-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0006_pokersessionmodel_presented_card_id'),
        ('meetings', '0003_backfill_room_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroommodel',
            name='audience_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meetingroommodel',
            name='is_permanent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='meetingroommodel',
            name='squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_rooms', to='estimation.squadmodel'),
        ),
        migrations.AddField(
            model_name='meetingroommodel',
            name='visibility',
            field=models.CharField(choices=[('restricted', 'Restrito'), ('workspace', 'Workspace')], db_index=True, default='restricted', max_length=12),
        ),
    ]
