# Generated by Django 5.2.15 on 2026-07-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_role_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleauditlog',
            name='actor_id',
            field=models.UUIDField(help_text='ID de quem realizou a ação'),
        ),
        migrations.AlterField(
            model_name='roleauditlog',
            name='target_user_id',
            field=models.UUIDField(help_text='ID de quem foi afetado'),
        ),
    ]
