# Generated by Django 5.2.16 on 2026-08-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_usermodel_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmodel',
            name='allowed_spaces',
            field=models.JSONField(blank=True, default=None, help_text='Spaces que este membro pode ver (null = todos, sem restrição).', null=True),
        ),
    ]
