# Generated by Django 5.2.16 on 2026-08-25

from django.db import migrations, models


def restrict_existing_non_owners(apps, schema_editor):
    Membership = apps.get_model("identity", "MembershipModel")
    Membership.objects.exclude(role="owner").filter(allowed_spaces__isnull=True).update(
        allowed_spaces=[]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0011_membershipmodel_allowed_spaces"),
    ]

    operations = [
        migrations.RunPython(
            restrict_existing_non_owners,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="membershipmodel",
            name="allowed_spaces",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Spaces que admin ou membro pode ver; só owner vê todos.",
                null=True,
            ),
        ),
    ]
