# Generated by Django 5.2.16 on 2026-09-01 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0013_personalaccesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClientModel',
            fields=[
                ('client_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCodeModel',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=64)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
