# Generated by Django 5.2.16 on 2026-09-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_oauthclientmodel_oauthauthorizationcodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclientmodel',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='oauthclientmodel',
            name='token_endpoint_auth_method',
            field=models.CharField(default='client_secret_post', max_length=32),
        ),
    ]
