# Generated by Django 5.2.15 on 2026-06-28 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleConnectionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('refresh_token', models.TextField()),
                ('access_token', models.TextField(blank=True)),
                ('expiry', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('revoked', 'Revogada')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão Google',
                'verbose_name_plural': 'Conexões Google',
                'db_table': 'google_connection',
            },
        ),
        migrations.CreateModel(
            name='MeetingRefModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(db_index=True, max_length=256)),
                ('card_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_meeting_ref',
            },
        ),
        migrations.CreateModel(
            name='OAuthStateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_oauth_state',
            },
        ),
    ]
