# Generated by Django 5.2.16 on 2026-08-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
        ('projects', '0031_projectdeletegrantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrefmodel',
            name='meeting_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrefmodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_meetings', to='projects.projectmodel'),
        ),
        migrations.AddField(
            model_name='meetingrefmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='meetingrefmodel',
            name='transcript_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
